import "~/styles/globals.css";

import { type Metadata } from "next";
import { ApolloWrapper } from "~/lib/apollo-provider";

export const metadata: Metadata = {
  title: "Create Jaydee App",
  description: "Generated by create-jaydee-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className="h-full">
      <body className="h-full">
        <ApolloWrapper>{children}</ApolloWrapper>
      </body>
    </html>
  );
}
